export const COMMON_MISSPELLINGS: ReadonlyMap<string, string> = new Map(
  Object.entries({
    accomodate: "accommodate",
    accomodated: "accommodated",
    accomodates: "accommodates",
    accomodating: "accommodating",
    acheive: "achieve",
    acheived: "achieved",
    acheives: "achieves",
    acheiving: "achieving",
    adress: "address",
    adressed: "addressed",
    adressing: "addressing",
    aggresive: "aggressive",
    apparant: "apparent",
    apparantly: "apparently",
    arguement: "argument",
    arguements: "arguments",
    basicly: "basically",
    becuase: "because",
    begining: "beginning",
    beleive: "believe",
    beleived: "believed",
    beleives: "believes",
    beleiving: "believing",
    calender: "calendar",
    cieling: "ceiling",
    collegue: "colleague",
    collegues: "colleagues",
    comming: "coming",
    concious: "conscious",
    conciously: "consciously",
    definate: "definite",
    definately: "definitely",
    dependancy: "dependency",
    dependancies: "dependencies",
    seperate: "separate",
    seperated: "separated",
    seperately: "separately",
    seperation: "separation",
    enviroment: "environment",
    enviroments: "environments",
    existance: "existence",
    familar: "familiar",
    finaly: "finally",
    goverment: "government",
    happend: "happened",
    immediatly: "immediately",
    implimentation: "implementation",
    impliment: "implement",
    implimented: "implemented",
    independant: "independent",
    intresting: "interesting",
    knowlege: "knowledge",
    lenght: "length",
    maintainance: "maintenance",
    neccessary: "necessary",
    occassion: "occasion",
    occured: "occurred",
    occurence: "occurrence",
    prefered: "preferred",
    prefering: "preferring",
    priviledge: "privilege",
    publically: "publicly",
    recieve: "receive",
    recieved: "received",
    recieves: "receives",
    recieving: "receiving",
    recomend: "recommend",
    recomendation: "recommendation",
    recomendations: "recommendations",
    refered: "referred",
    refering: "referring",
    relevent: "relevant",
    responsiblity: "responsibility",
    sucess: "success",
    sucessful: "successful",
    sucessfully: "successfully",
    targetted: "targeted",
    teh: "the",
    wierd: "weird",
    writting: "writing",
  }),
);

export function preserveCase(input: string, replacement: string): string {
  if (input === input.toUpperCase()) {
    return replacement.toUpperCase();
  }

  if (input.charAt(0) === input.charAt(0).toUpperCase()) {
    return replacement.charAt(0).toUpperCase() + replacement.slice(1);
  }

  return replacement;
}
